INSERT INTO TB_METHOD (id, description, created_at, updated_at, is_active, version)
VALUES
  (UUID(), 'GET', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, 1),
  (UUID(), 'POST', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, 1),
  (UUID(), 'PUT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, 1),
  (UUID(), 'DELETE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, 1),
  (UUID(), 'PATCH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, 1),
  (UUID(), 'OPTIONS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, 1),
  (UUID(), 'HEAD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, 1);

INSERT INTO TB_AUTHORIZATION (id, description, created_at, updated_at, is_active, version)
VALUES
  (UUID(), '/user GET', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, 1),
  (UUID(), '/user POST', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, 1),
  (UUID(), '/user PUT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, 1),
  (UUID(), '/user DELETE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, 1);

INSERT INTO TB_ROLE (id, description, created_at, updated_at, is_active, version)
VALUES
  (UUID(), 'Administrator', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, 1),
  (UUID(), 'Regular User', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, 1);
